# Example with running multiple services of same image, load balanced using Caddy reverse-proxy.

# Update Caddyfile with instructions given in it.

# Run following command to build the image before running docker compose.
#   docker build -f build.Dockerfile -t quickretro-app .

# Cold start
#   docker compose -f compose.multiservice.yml up

# Restart services.
# Containers are NOT deleted, just STOPPED and STARTED. No data is lost.
# Use case: ENV variable update.
#   docker compose -f compose.multiservice.yml stop
#   docker compose -f compose.multiservice.yml start

# Deletes containers and networks, then create them back from already built/pulled images.
# Volumes and images are retained, so data in volumes is not lost.
# Use case: if the previous "Restart services" steps are inadequate.
#   docker compose -f compose.multiservice.yml down
#   docker compose -f compose.multiservice.yml up

# Hard reset: removes containers, networks, volumes, and images.
# ALL data stored in volumes will be lost (including Redis data).
# Use case: code changes, new images, or if previous steps are inadequate.
#   docker compose -f compose.multiservice.yml down --rmi "all" --volumes
#   docker compose -f compose.multiservice.yml up

x-app-defaults: &app-defaults
    image: quickretro-app
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      # Load from .env file in same directory as the compose file. 
      # To create file, in CLI: echo "REDIS_CONNSTR=redis://redis:6379/0" > .env
      # DO NOT create file from Windows. It creates Unicode text, UTF-16, little-endian text, with CRLF line terminators.
      - REDIS_CONNSTR=${REDIS_CONNSTR}  
      # Default Redis (No Auth or ACL). Outside docker - redis://localhost:6379/0
      # - REDIS_CONNSTR=redis://redis:6379/0 
      # Using Redis ACL with Username & Password. Outside docker - redis://app-user:mysecretpassword@localhost:6379/0
      # - REDIS_CONNSTR=redis://app-user:mysecretpassword@redis:6379/0
      - TURNSTILE_ENABLED=${TURNSTILE_ENABLED}
      - TURNSTILE_SITE_KEY=${TURNSTILE_SITE_KEY}
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}          
    networks:
      - redisnet
      - proxynet
    expose:
      - 8080

services:
  redis:
    image: "redis:8.0.1-alpine"
    ############## Redis ACL ##############
    # volumes:
    #   - ./redis/users.acl:/usr/local/etc/redis/users.acl
    # command: redis-server --aclfile /usr/local/etc/redis/users.acl
    # # command: ["redis-server", "--aclfile", "/usr/local/etc/redis/users.acl"]
    ############## Redis ACL ##############
    restart: always
    networks:
      - redisnet
    expose:
      - 6379
    volumes:
      - redis_data:/data  

  app:
    <<: *app-defaults

  app01:
    <<: *app-defaults     

  caddy:
    image: caddy:2.10.0-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      - app
    networks:
      - proxynet          
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  redis_data:
  caddy_data:
  caddy_config:      

networks:
  redisnet:
    name: redisnet
  proxynet:
    name: proxynet