# Example with running multiple services of same image with replicas, load balanced by Docker internally.

# Run docker compose.
#   docker compose -f compose.replicas.yml up
# To stop and remove compose created items
#   docker compose -f compose.replicas.yml down --rmi "all" --volumes

services:
  redis:
    image: "redis:7.2.3-alpine"
    ############## Redis ACL ##############
    # volumes:
    #   - ./redis/users.acl:/usr/local/etc/redis/users.acl
    # command: redis-server --aclfile /usr/local/etc/redis/users.acl
    # # command: ["redis-server", "--aclfile", "/usr/local/etc/redis/users.acl"]
    ############## Redis ACL ##############
    restart: always
    networks:
      - redisnet
    # ports:
    #   - "6379:6379"
    expose:
      - 6379

  app:
    build:
      context: .
      dockerfile: build.Dockerfile
    restart: unless-stopped  
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - redis
    environment:
      - REDIS_CONNSTR=redis://redis:6379/0  # Default Redis (No Auth or ACL). Outside docker - redis://localhost:6379/0
      ############## Redis ACL ##############
      # - REDIS_CONNSTR=redis://app-user:mysecretpassword@redis:6379/0  # Using ACL with Username & Password. Outside docker - redis://app-user:mysecretpassword@localhost:6379/0
      ############## Redis ACL ##############      
    networks:
      - redisnet
      - proxynet
    expose:
      - 8080

  caddy:
    image: caddy:2.7.6-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      - app
    networks:
      - proxynet          
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:      

networks:
  redisnet:
    name: redisnet
  proxynet:
    name: proxynet