# For local development only. Ports are exposed to host machine. No reverse-proxy.

# Run docker compose.
#   docker compose -f compose.01.yml up
# To stop and remove compose created items
#   docker compose -f compose.01.yml down --rmi "all" --volumes

services:
  redis:
    image: "redis:7.2.3-alpine"
    ############## Redis ACL ##############
    # volumes:
    #   - ./redis/users.acl:/usr/local/etc/redis/users.acl
    # command: redis-server --aclfile /usr/local/etc/redis/users.acl
    # # command: ["redis-server", "--aclfile", "/usr/local/etc/redis/users.acl"]
    ############## Redis ACL ##############    
    restart: always
    networks:
      - redisnet
    ports:
      - "6379:6379"

  app:
    image: "vijeesh82/quickretro-app"
    restart: unless-stopped  
    depends_on:
      - redis
    environment:
      - REDIS_CONNSTR=redis://redis:6379/0  # Default Redis (No Auth or ACL). Outside docker - redis://localhost:6379/0
      ############## Redis ACL ##############
      # - REDIS_CONNSTR=redis://app-user:mysecretpassword@redis:6379/0  # Using ACL with Username & Password. Outside docker - redis://app-user:mysecretpassword@localhost:6379/0
      ############## Redis ACL ##############
    networks:
      - redisnet
    ports:
      - "8080:8080"   

networks:
  redisnet:
    name: redisnet